# x_takeoff: current position x
# y_takeoff: current position y
z_takeoff: 3 # m

hover_time: 10 # second(s)

num_of_target: 3
x_pos: [0, 6, 6, 0] # m
y_pos: [0, 0, 6, 6] # m
z_pos: [5, 6, 7, 8] # m
target_error: 0.1 # m

num_of_goal: 3
latitude: [21.0065275, 21.0066507, 21.0065305]
longitude: [105.8428991, 105.8431418, 105.8432921]
altitude: [5, 6, 7] # m
goal_error: 0.3 # m

v_desired: 0.3 # m/s
human_trig: false
